import "./globals.css";

export const metadata = {
  title: "GameDB",
  description: "Generated by Amrit Reddy",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-slate-800 text-white" lang="en">
      <body>{children}</body>
    </html>
  );
}
